### ISSUE TITLE
Override sample gender

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ClinCNV#14]
Hi German,

Alex Seitz had a **male** patient with a large duplication on chrX, so it was determined to be a **female**.
Is there a way to overwrite the gender for a sample?

Best,
  Marc

The data of the case can be found here: /mnt/users/ahsturm1/Sandbox/ClinCNV/bug_gender_clustering/

**Comment by alex-seitz** [comment]
In addition to the large duplication on chrX, this patient also had a large deletion on chrY.

**Comment by GermanDemidov** [comment]
Large deletion on Y and large duplication on X? Is it truly male? There
is no manual assignment of genders, but i may implement it on Friday.
This is one in a million case... 

>>> Marc Sturm <notifications@github.com> 16.10.19 13:18 >>>
Hi German,

Alex Seitz had a **male** patient with a large duplication on chrX, so
it was determined to be a **female**.
Is there a way to overwrite the gender for a sample?

Best,
  Marc

The data of the case can be found here:
/mnt/users/ahsturm1/Sandbox/ClinCNV/bug_gender_clustering/

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/imgag/ClinCNV/issues/14

**Comment by alex-seitz** [comment]
Hi,
yes, it the patient is definitely male. The sry gene is unaffected.

Best,
Alex

**Comment by marc-sturm** [comment]
Yes, you are right. This is a very rare case.
You you should take care of #12 and #13 first.

**Comment by GermanDemidov** [comment]
I know that it is too late, but now it is possible with --sex flag. There only 2 modifiers are accepted: "M" or "F" (not "male" or any others). Works only if you speciify the sample (so it is still not possible to give a table of sexes for the cohort). Tested and worked.
