### ISSUE TITLE
Error in writeLines [...] cannot open the connection

### ISSUE THREAD

**Issue by frmacomber** [imgag/ClinCNV#20]
Hi ClinCNV developers,

running ClinCNV with the provided test data produced an error which we couldn't resolve.  All packages are installed as indicated (install_deps_clincnv.R).

[log.txt](https://github.com/imgag/ClinCNV/files/6441905/log.txt)

Thanks a lot!
Best
PS:  running on HPC w/ ubuntu 18.04.5.

**Comment by GermanDemidov** [comment]
Hi  frmacomber,

seems that the tool actually worked, 2 samples were analyzed (can you check that the results for the first 2 samples make sense?). For the 3rd patient it looks that the tool could not write to the file, "cannot open the connection" basically means that there was a system error, not sure, the file was removed in the middle? does this file already exists and have no permission to overwrite?

It could be an error of the tool, but the log says that there was an error in writeLines which is an R function, and cannot open the connection indicates that the file is not available.

Overall the log looks a bit strange - no probes were filtered out due to extreme GC/low coverage...Is it a very short targeted panel?
